### ISSUE TITLE
Possible error on zzzRemoveNodes.cfg

### ISSUE THREAD

**Issue by Tonas1997** [theonegalen/UnKerballedStart#29]
I was looking for a couple of missing parts and noticed that their cache configuration ended up with two `TechRequired` fields. I checked for any patches that might have caused this and... well, UKS's `zzzRemoveNodes.cfg` file seems to add an extra field:

```@PART[*]:HAS[#TechRequired[storageTech]]:NEEDS[CommunityTechTree]:LAST[zzzUnKerballedStart]
{
	TechRequired = recycling
}
//merged with Scanning Tech
@PART[*]:HAS[#TechRequired[fieldScience]]:NEEDS[CommunityTechTree]:LAST[zzzUnKerballedStart]
{
	TechRequired = scienceTech
}
//merged with Advance Unmanned
@PART[*]:HAS[#TechRequired[automation]]:NEEDS[CommunityTechTree]:LAST[zzzUnKerballedStart]
{
	TechRequired = advUnmanned
}
//merged with Advanced Science Tech
@PART[*]:HAS[#TechRequired[specializedScienceTech]]:NEEDS[CommunityTechTree]:LAST[zzzUnKerballedStart]
{
	TechRequired = advScienceTech
}
```

You probably meant to add an `@` before `TechRequired` 😁

**Comment by theonegalen** [comment]
Fixed with https://github.com/theonegalen/UnKerballedStart/commit/8ad63d1501a4383f9a5a51ea1d9d20bd79026235
