### ISSUE TITLE
The "Unresearcheable" vs. "Unresearchable" bug

### ISSUE THREAD

**Issue by Gordon-Dry** [theonegalen/UnKerballedStart#31]
Squad uses
`TechRequired = Unresearcheable`
and so do many mods.

There is an 'e' inside - do not use "TechRequired = Unresearchable".

Also https://wiki.kerbalspaceprogram.com/wiki/CFG_File_Documentation#Editor_Parameters says so.

The only related files I found are:
```
GameData\UnKerballedStart\Mod Support\CNAR.cfg
GameData\UnKerballedStart\Mod Support\DeadlyReentry.cfg
GameData\UnKerballedStart\Mod Support\KAX.cfg
GameData\UnKerballedStart\Mod Support\kOS.cfg
GameData\UnKerballedStart\Mod Support\NearFutureLaunchVehicles.cfg
GameData\UnKerballedStart\Mod Support\ReStockPlus.cfg
GameData\UnKerballedStart\Mod Support\SETIprobeParts.cfg
GameData\UnKerballedStart\parts\UKSsolidBoosterRT1.cfg
GameData\UnKerballedStart\UnKerballedStart.cfg
```
But those affect a lot of parts.

Please always use
`TechRequired = Unresearcheable`

**Comment by Gordon-Dry** [comment]
^Updated for typos.

**Comment by theonegalen** [comment]
Thanks! I'll update this.

**Comment by theonegalen** [comment]
Fixed in https://github.com/theonegalen/UnKerballedStart/commit/f5d0fc251f6c216389df79ac2aa20fb714a6a71e
